### ISSUE TITLE
DeepMind Health

### ISSUE THREAD

**Issue by philipobrien** [acoravos/healthcare-blockchains#15]
Hi, I just came across [your blog post](https://blog.andreacoravos.com/where-are-the-healthcare-blockchains-8fcf6a3e28f8). I'm not actively involved in this space, but I remember coming across an article by DeepMind discussing how they are using blockchain as part of their [Verifiable Data Audit](https://deepmind.com/blog/trust-confidence-verifiable-data-audit/). You might want to include this?

**Comment by acoravos** [comment]
Brilliant find. Will add.

**Comment by acoravos** [comment]
@philipobrien -- Added DeepMind Health. Thanks!

**Comment by philipobrien** [comment]
Sorry, busy few days, never got a chance to send a PR. Glad it was useful.
