### ISSUE TITLE
List of healthcare ICOs/Token Offerings

### ISSUE THREAD

**Issue by vincek39** [acoravos/healthcare-blockchains#16]
fyi, Here's a link to my list of 38+ healthcare ICOs/token offerings:

https://docs.google.com/spreadsheets/d/1TANOZmuYtVhyn1C9PV6YLsOBlQNOEOBExB7u2_Kkork/edit#gid=0

Vince

**Comment by acoravos** [comment]
This is excellent -- I'm going to add this to the main page and cite you. Thanks!
